name: hostel_finding
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.13.4
  firebase_database: ^10.4.0
  rename: ^3.0.2
  image_picker: ^1.0.0
  firebase_storage: ^11.0.0
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/logo_png.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg" # Ensure this file exists!
  # adaptive_icon_background: "#3A7BD5"
  adaptive_icon_foreground: "assets/logo.jpg"
