// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMU0RJbpKIwrdh7RJNM2EmQ-LASmQV-iI',
    appId: '1:784727553351:web:0cf265980a124b26e64862',
    messagingSenderId: '784727553351',
    projectId: 'hostel-finder-65872',
    authDomain: 'hostel-finder-65872.firebaseapp.com',
    storageBucket: 'hostel-finder-65872.firebasestorage.app',
    measurementId: 'G-XBHSQBP1ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAxBPcXFmdpq6xyV18BXBtZTIwgMe9bh4',
    appId: '1:784727553351:android:4059c7ab71aa83e0e64862',
    messagingSenderId: '784727553351',
    projectId: 'hostel-finder-65872',
    storageBucket: 'hostel-finder-65872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUd8LrvwEttwKNwjZKHomD5PUvGuvL-IA',
    appId: '1:784727553351:ios:c3dfd61e1d8ee406e64862',
    messagingSenderId: '784727553351',
    projectId: 'hostel-finder-65872',
    storageBucket: 'hostel-finder-65872.firebasestorage.app',
    iosClientId:
        '784727553351-56bug5472dusq1d1puc8hh93eik2lnud.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelFinding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUd8LrvwEttwKNwjZKHomD5PUvGuvL-IA',
    appId: '1:784727553351:ios:c3dfd61e1d8ee406e64862',
    messagingSenderId: '784727553351',
    projectId: 'hostel-finder-65872',
    storageBucket: 'hostel-finder-65872.firebasestorage.app',
    iosClientId:
        '784727553351-56bug5472dusq1d1puc8hh93eik2lnud.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelFinding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMU0RJbpKIwrdh7RJNM2EmQ-LASmQV-iI',
    appId: '1:784727553351:web:88df333e1734c56ee64862',
    messagingSenderId: '784727553351',
    projectId: 'hostel-finder-65872',
    authDomain: 'hostel-finder-65872.firebaseapp.com',
    storageBucket: 'hostel-finder-65872.firebasestorage.app',
    measurementId: 'G-YNLJGFNKW0',
  );
}
